### ISSUE TITLE
pip install --user => No module named base16_shell_preview.__main__

### ISSUE THREAD

**Issue by cben** [nvllsvm/base16-shell-preview#4]
Hi, on Fedora 30 linux, after `pip install base16-shell-preview --user`, running `base16-shell-preview` errors out:
```fish
~ $ base16-shell-preview
Traceback (most recent call last):
  File "/home/bpaskinc/.local/bin/base16-shell-preview", line 11, in <module>
    load_entry_point('base16-shell-preview==0.6.0', 'console_scripts', 'base16-shell-preview')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ImportError: No module named base16_shell_preview.__main__

~ $ ls ~/.local/lib/python2.7/site-packages/base16_shell_preview*
/home/bpaskinc/.local/lib/python2.7/site-packages/base16_shell_preview:
__main__.py  __main__.pyc

/home/bpaskinc/.local/lib/python2.7/site-packages/base16_shell_preview-0.6.0-py2.7.egg-info:
dependency_links.txt  entry_points.txt  installed-files.txt  PKG-INFO  SOURCES.txt  top_level.txt

~ $ cat /home/bpaskinc/.local/lib/python2.7/site-packages/base16_shell_preview-0.6.0-py2.7.egg-info/installed-files.txt 
../../../../bin/base16-shell-preview
../base16_shell_preview/__main__.py
../base16_shell_preview/__main__.pyc
PKG-INFO
SOURCES.txt
dependency_links.txt
entry_points.txt
top_level.txt

~ $ python2.7 -m base16_shell_preview
/usr/bin/python2.7: No module named base16_shell_preview
```

My guess is that it's not enough to have `__main__.py`, the directory has to be importable as a module, and indeed adding an empty `__init__.py` helped me:
```fish
~ $ touch /home/bpaskinc/.local/lib/python2.7/site-packages/base16_shell_preview/__init__.py
~ $ python2.7 -m base16_shell_preview
usage: base16-shell-preview [-h] [--version] [--sort-bg]
base16-shell-preview: error: please set the BASE16_SHELL environment variable to the local repository path.
~ $ base16-shell-preview
usage: base16-shell-preview [-h] [--version] [--sort-bg]
base16-shell-preview: error: please set the BASE16_SHELL environment variable to the local repository path.
```

**Comment by cben** [comment]
However, `pip3 install base16-shell-preview --user` works out of the box, without __init__.py :tada:

Consider suggesting `pip3` in the README.
(I think environments differ by what bare `pip` means, but `pip3` exists pretty much anywhere python 3.x exists?)

**Comment by andrewrabert** [comment]
0.6.1 fixes Python 2 support. I'll be keeping the README as just `pip` for now. Long term plan is to rewrite this in a compiled language and distribute a static binary instead - especially since the next version of macOS will be removing Python entirely.
